#!/usr/bin/env node
/**
 * CKB Node Dashboard — server.js
 * Serves the dashboard UI and proxies JSON-RPC calls to the local CKB node.
 * Reads config from config.json (generated by setup.sh).
 */

const http = require('http');
const fs   = require('fs');
const path = require('path');

// ── Config ────────────────────────────────────────────────────────────────────
const CONFIG_PATH = path.join(__dirname, '..', 'config.json');

function loadConfig() {
  try {
    const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
    return JSON.parse(raw);
  } catch (e) {
    console.error(`ERROR: Cannot read config.json at ${CONFIG_PATH}`);
    console.error('Run setup.sh first to configure your node.');
    process.exit(1);
  }
}

const config   = loadConfig();
const CKB_HOST = config.node_host || '127.0.0.1';
const CKB_PORT = config.node_port || 8114;
const PORT     = config.dashboard_port || 3000;
const DIR      = path.join(__dirname, 'public');

// ── Proxy ─────────────────────────────────────────────────────────────────────
function proxyRpc(body, res) {
  const opts = {
    hostname: CKB_HOST,
    port:     CKB_PORT,
    path:     '/',
    method:   'POST',
    headers: {
      'Content-Type':   'application/json',
      'Content-Length': Buffer.byteLength(body),
    },
    timeout: 8000,
  };

  const req = http.request(opts, (ckbRes) => {
    res.writeHead(200, {
      'Content-Type':                'application/json',
      'Access-Control-Allow-Origin': '*',
    });
    ckbRes.pipe(res);
  });

  req.on('error', (e) => {
    res.writeHead(502, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: { code: -32000, message: `Node unreachable: ${e.message}` } }));
  });

  req.on('timeout', () => {
    req.destroy();
    res.writeHead(504, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: { code: -32000, message: 'Node timeout' } }));
  });

  req.write(body);
  req.end();
}

// ── Static file server ────────────────────────────────────────────────────────
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.json': 'application/json',
  '.ico':  'image/x-icon',
  '.png':  'image/png',
};

function serveStatic(reqPath, res) {
  const rel      = reqPath === '/' ? 'index.html' : reqPath.replace(/^\//, '');
  const filePath = path.join(DIR, rel);

  // Prevent directory traversal
  if (!filePath.startsWith(DIR)) {
    res.writeHead(403); res.end('Forbidden'); return;
  }

  fs.readFile(filePath, (err, data) => {
    if (err) { res.writeHead(404); res.end('Not found'); return; }
    const mime = MIME[path.extname(filePath)] || 'application/octet-stream';
    res.writeHead(200, { 'Content-Type': mime });
    res.end(data);
  });
}

// ── Main ─────────────────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  if (req.method === 'OPTIONS') {
    res.writeHead(204, {
      'Access-Control-Allow-Origin':  '*',
      'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    });
    res.end();
    return;
  }

  if (req.url === '/rpc' && req.method === 'POST') {
    let body = '';
    req.on('data', d => { body += d; if (body.length > 65536) req.destroy(); });
    req.on('end',  ()  => proxyRpc(body, res));
    return;
  }

  // Inject node info into config endpoint
  if (req.url === '/config' && req.method === 'GET') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ node_host: CKB_HOST, node_port: CKB_PORT }));
    return;
  }

  serveStatic(req.url, res);
});

server.listen(PORT, '0.0.0.0', () => {
  console.log(`CKB Node Dashboard`);
  console.log(`  Dashboard:  http://0.0.0.0:${PORT}`);
  console.log(`  Node RPC:   http://${CKB_HOST}:${CKB_PORT}`);
});
